import { db } from '@/lib/db';
import { auth } from '@clerk/nextjs/server';
import { NextResponse } from 'next/server';

/**
 * POST /api/profile/dismiss-banner
 * Dismiss the auto-generated banner
 */
export async function POST() {
  try {
    const { userId } = await auth();

    if (!userId) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const user = await db.user.findUnique({
      where: { clerkId: userId },
      include: { profile: true },
    });

    if (!user?.profile) {
      return NextResponse.json({ error: 'Profile not found' }, { status: 404 });
    }

    await db.profile.update({
      where: { id: user.profile.id },
      data: {
        autoGeneratedDismissed: true,
      },
    });

    return NextResponse.json({ success: true });
  } catch (error) {
    console.error('Error dismissing banner:', error);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}
