/**
 * Snap View Types
 *
 * Data schema for the recruiter-focused Snap View — a wide-format,
 * single-viewport professional summary that tells a hiring manager
 * everything they need in under 30 seconds.
 *
 * This data is AI-generated from raw profile data, distilled to show
 * only what matters for hiring decisions.
 */

// ============================================================================
// CORE DATA STRUCTURE
// ============================================================================

/**
 * Complete snap view payload — the contract between the generation
 * pipeline (AI or algorithmic) and the snap view renderer.
 */
export interface SnapViewData {
  /** ISO timestamp when this snap was generated */
  generatedAt: string;

  /** AI-crafted one-line professional tagline (not the raw headline) */
  tagline: string;

  /** Key numeric stats for the at-a-glance stat bar */
  stats: SnapViewStats;

  /** Condensed career timeline — role, company, dates, one highlight each */
  careerTimeline: SnapCareerEntry[];

  /** Education entries — degree, institution, year, optional distinction */
  education: SnapEducationEntry[];

  /** Skills grouped into meaningful domain clusters (3-4 groups) */
  skillClusters: SnapSkillCluster[];

  /** Top 3 most impactful projects with one-line descriptions */
  keyProjects: SnapProject[];

  /** 2-3 sentence recruiter pitch answering "Why interview this person?" */
  recruiterBrief: string;

  /** Short certification names (e.g. "AWS Solutions Architect") */
  certifications: string[];

  /** Short award names (e.g. "Dean's List", "Patent Holder") */
  awards: string[];

  /** Whether this was generated by AI (true) or computed algorithmically (false) */
  isAIGenerated: boolean;
}

// ============================================================================
// SUB-STRUCTURES
// ============================================================================

export interface SnapViewStats {
  yearsOfExperience: number;
  companiesCount: number;
  skillsCount: number;
  /** Highest degree abbreviation, e.g. "PhD", "MS", "BS", or null */
  highestDegree: string | null;
}

export interface SnapCareerEntry {
  role: string;
  company: string;
  /** Human-readable date range, e.g. "Jan 2022 → Present" */
  period: string;
  /** One-line impact highlight (AI-generated, <15 words) */
  highlight: string;
  isCurrent: boolean;
}

export interface SnapEducationEntry {
  /** Short degree name, e.g. "MS Computer Science" */
  degree: string;
  institution: string;
  /** Graduation year, e.g. "2019" */
  year: string;
  /** Optional distinction like GPA or honors */
  distinction?: string;
}

export interface SnapSkillCluster {
  /** Category name, e.g. "Frontend", "Cloud & DevOps", "Data" */
  category: string;
  /** Top skills in this cluster (3-5 each) */
  skills: string[];
}

export interface SnapProject {
  name: string;
  /** One-line impact description (AI-generated, quantitative when possible) */
  impact: string;
  /** Top 2-3 technologies used */
  tech: string[];
}
