import { db } from '@/lib/db';
import type { NormalizedImportResult } from '@/services/import/types';
import { auth, currentUser } from '@clerk/nextjs/server';
import type { DataSource } from '@prisma/client';
import { NextRequest, NextResponse } from 'next/server';

// Helper to safely cast string to DataSource enum
const toDataSource = (source: string | undefined): DataSource => {
  return (source || 'MANUAL') as DataSource;
};

/**
 * POST /api/onboarding/complete
 * Complete onboarding - create/update profile with imported data
 */
export async function POST(request: NextRequest) {
  try {
    const { userId } = await auth();

    if (!userId) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const body = await request.json();
    const { importedData } = body;

    // Get or create user
    let user = await db.user.findUnique({
      where: { clerkId: userId },
      include: { profile: true },
    });

    if (!user) {
      const clerkUser = await currentUser();
      if (!clerkUser?.emailAddresses?.[0]?.emailAddress) {
        return NextResponse.json({ error: 'Unable to get user details' }, { status: 400 });
      }

      user = await db.user.create({
        data: {
          clerkId: userId,
          email: clerkUser.emailAddresses[0].emailAddress,
        },
        include: { profile: true },
      });
    }

    // Merge imported data
    const mergedProfile = mergeImportedData(importedData);

    // Generate handle from name or email
    let handle = generateHandle(mergedProfile.firstName, mergedProfile.lastName, user.email);

    // Ensure handle is unique
    handle = await ensureUniqueHandle(handle, user.profile?.id);

    // Create or update profile
    if (!user.profile) {
      // Create new profile
      const profile = await db.profile.create({
        data: {
          userId: user.id,
          handle,
          firstName: mergedProfile.firstName || 'New',
          lastName: mergedProfile.lastName,
          headline: mergedProfile.headline,
          summary: mergedProfile.summary,
          location: mergedProfile.location,
          avatarUrl: mergedProfile.avatarUrl,
          status: 'PUBLIC', // Make profile public by default
          // TODO: Uncomment after running migration
          // isAutoGenerated: true,
          // autoGeneratedAt: new Date(),
          // Set sources for provenance
          // firstNameSource: toDataSource(mergedProfile.firstNameSource),
          // lastNameSource: toDataSource(mergedProfile.lastNameSource),
          // headlineSource: toDataSource(mergedProfile.headlineSource),
          // summarySource: toDataSource(mergedProfile.summarySource),
          // locationSource: toDataSource(mergedProfile.locationSource),
          // avatarUrlSource: toDataSource(mergedProfile.avatarUrlSource),
        },
      });

      // Create contact info
      await db.contactInfo.create({
        data: {
          profileId: profile.id,
          email: mergedProfile.email,
          emailPublic: false,
          phone: mergedProfile.phone,
          phonePublic: false,
          website: mergedProfile.website,
        },
      });

      // Create skills
      if (mergedProfile.skills?.length) {
        await db.skill.createMany({
          data: mergedProfile.skills.map((skill, index) => ({
            profileId: profile.id,
            name: skill.name,
            source: toDataSource(skill.source),
            sortOrder: index,
          })),
          skipDuplicates: true,
        });
      }

      // Create projects
      if (mergedProfile.projects?.length) {
        await db.project.createMany({
          data: mergedProfile.projects.map((project, index) => ({
            profileId: profile.id,
            title: project.title,
            description: project.description,
            shortDesc: project.shortDesc,
            url: project.url,
            repoUrl: project.repoUrl,
            techStack: project.techStack || [],
            featured: project.featured || index < 3,
            source: toDataSource(project.source),
            sortOrder: index,
            githubStars: project.ghStars,
            githubForks: project.ghForks,
            githubLanguage: project.ghLanguage,
          })),
        });
      }

      // Create work experiences
      if (mergedProfile.experiences?.length) {
        await db.workExperience.createMany({
          data: mergedProfile.experiences.map((exp, index) => ({
            profileId: profile.id,
            company: exp.company,
            role: exp.role,
            location: exp.location,
            startDate: exp.startDate ? new Date(exp.startDate) : new Date(),
            endDate: exp.endDate ? new Date(exp.endDate) : null,
            isCurrent: exp.isCurrent || false,
            description: exp.description,
            bullets: exp.bullets || [],
            tags: exp.tags || [],
            source: toDataSource(exp.source),
            sortOrder: index,
          })),
        });
      }

      // Create education
      if (mergedProfile.educations?.length) {
        await db.education.createMany({
          data: mergedProfile.educations.map((edu, index) => ({
            profileId: profile.id,
            institution: edu.institution,
            degree: edu.degree,
            fieldOfStudy: edu.fieldOfStudy,
            startDate: edu.startDate ? new Date(edu.startDate) : null,
            endDate: edu.endDate ? new Date(edu.endDate) : null,
            isCurrent: edu.isCurrent || false,
            gpa: edu.gpa,
            source: toDataSource(edu.source),
            sortOrder: index,
          })),
        });
      }

      // Create links
      if (mergedProfile.links?.length) {
        await db.link.createMany({
          data: mergedProfile.links.map((link, index) => ({
            profileId: profile.id,
            type: mapLinkType(link.type),
            url: link.url,
            label: link.label,
            source: toDataSource(link.source),
            sortOrder: index,
          })),
        });
      }
    } else {
      // Update existing profile (merge mode)
      await db.profile.update({
        where: { id: user.profile.id },
        data: {
          firstName: mergedProfile.firstName || user.profile.firstName,
          lastName: mergedProfile.lastName || user.profile.lastName,
          headline: mergedProfile.headline || user.profile.headline,
          summary: mergedProfile.summary || user.profile.summary,
          location: mergedProfile.location || user.profile.location,
          avatarUrl: mergedProfile.avatarUrl || user.profile.avatarUrl,
          // TODO: Uncomment after running migration
          // isAutoGenerated: true,
          // autoGeneratedAt: new Date(),
        },
      });

      // Merge skills (avoid duplicates)
      if (mergedProfile.skills?.length) {
        for (const skill of mergedProfile.skills) {
          await db.skill.upsert({
            where: {
              profileId_name: {
                profileId: user.profile.id,
                name: skill.name,
              },
            },
            create: {
              profileId: user.profile.id,
              name: skill.name,
              source: toDataSource(skill.source),
              sortOrder: 0,
            },
            update: {}, // Don't update if exists
          });
        }
      }

      // Add new projects (dedupe by repoUrl or title)
      if (mergedProfile.projects?.length) {
        const existingProjects = await db.project.findMany({
          where: { profileId: user.profile.id },
          select: { title: true, repoUrl: true },
        });

        const existingKeys = new Set(
          existingProjects.map((p) => p.repoUrl || p.title.toLowerCase())
        );

        const newProjects = mergedProfile.projects.filter(
          (p) => !existingKeys.has(p.repoUrl || p.title.toLowerCase())
        );

        if (newProjects.length) {
          await db.project.createMany({
            data: newProjects.map((project, index) => ({
              profileId: user.profile!.id,
              title: project.title,
              description: project.description,
              shortDesc: project.shortDesc,
              url: project.url,
              repoUrl: project.repoUrl,
              techStack: project.techStack || [],
              featured: project.featured || false,
              source: toDataSource(project.source),
              sortOrder: existingProjects.length + index,
              githubStars: project.ghStars,
              githubForks: project.ghForks,
              githubLanguage: project.ghLanguage,
            })),
          });
        }
      }
    }

    // TODO: Uncomment after running migration
    // Mark onboarding as completed
    // await db.user.update({
    //   where: { id: user.id },
    //   data: {
    //     onboardingCompleted: true,
    //     onboardingCompletedAt: new Date(),
    //   },
    // });

    return NextResponse.json({
      success: true,
      handle,
      message: 'Profile created successfully',
    });
  } catch (error) {
    console.error('Error completing onboarding:', error);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}

/**
 * Merge data from multiple import sources
 */
function mergeImportedData(importedData: Record<string, NormalizedImportResult | undefined>) {
  const merged: {
    firstName?: string;
    lastName?: string;
    headline?: string;
    summary?: string;
    location?: string;
    avatarUrl?: string;
    email?: string;
    phone?: string;
    website?: string;
    firstNameSource?: string;
    lastNameSource?: string;
    headlineSource?: string;
    summarySource?: string;
    locationSource?: string;
    avatarUrlSource?: string;
    skills: Array<{ name: string; source: string }>;
    projects: Array<{
      title: string;
      description?: string;
      shortDesc?: string;
      url?: string;
      repoUrl?: string;
      techStack?: string[];
      featured?: boolean;
      source: string;
      ghStars?: number;
      ghForks?: number;
      ghLanguage?: string;
    }>;
    experiences: Array<{
      company: string;
      role: string;
      location?: string;
      startDate?: string;
      endDate?: string;
      isCurrent?: boolean;
      description?: string;
      bullets?: string[];
      tags?: string[];
      source: string;
    }>;
    educations: Array<{
      institution: string;
      degree?: string;
      fieldOfStudy?: string;
      startDate?: string;
      endDate?: string;
      isCurrent?: boolean;
      gpa?: string;
      source: string;
    }>;
    links: Array<{
      type: string;
      url: string;
      label?: string;
      source: string;
    }>;
  } = {
    skills: [],
    projects: [],
    experiences: [],
    educations: [],
    links: [],
  };

  // Priority: resume > github > manual links
  const sources = ['resume', 'github', 'links'];

  for (const sourceKey of sources) {
    const data = importedData[sourceKey];
    if (!data) continue;

    // Profile info (first wins)
    if (data.profile) {
      if (!merged.firstName && data.profile.firstName) {
        merged.firstName = data.profile.firstName;
        merged.firstNameSource = data.source;
      }
      if (!merged.lastName && data.profile.lastName) {
        merged.lastName = data.profile.lastName;
        merged.lastNameSource = data.source;
      }
      if (!merged.headline && data.profile.headline) {
        merged.headline = data.profile.headline;
        merged.headlineSource = data.source;
      }
      if (!merged.summary && data.profile.summary) {
        merged.summary = data.profile.summary;
        merged.summarySource = data.source;
      }
      if (!merged.location && data.profile.location) {
        merged.location = data.profile.location;
        merged.locationSource = data.source;
      }
      if (!merged.avatarUrl && data.profile.avatarUrl) {
        merged.avatarUrl = data.profile.avatarUrl;
        merged.avatarUrlSource = data.source;
      }
    }

    // Contact info
    if (data.contactInfo) {
      if (!merged.email && data.contactInfo.email) {
        merged.email = data.contactInfo.email;
      }
      if (!merged.phone && data.contactInfo.phone) {
        merged.phone = data.contactInfo.phone;
      }
      if (!merged.website && data.contactInfo.website) {
        merged.website = data.contactInfo.website;
      }
    }

    // Append arrays (dedupe later)
    if (data.skills?.length) {
      merged.skills.push(...data.skills.map((s) => ({ name: s.name, source: data.source })));
    }
    if (data.projects?.length) {
      merged.projects.push(...data.projects.map((p) => ({ ...p, source: data.source })));
    }
    if (data.experiences?.length) {
      merged.experiences.push(...data.experiences.map((e) => ({ ...e, source: data.source })));
    }
    if (data.educations?.length) {
      merged.educations.push(...data.educations.map((e) => ({ ...e, source: data.source })));
    }
    if (data.links?.length) {
      merged.links.push(...data.links.map((l) => ({ ...l, source: data.source })));
    }
  }

  // Deduplicate skills
  const seenSkills = new Set<string>();
  merged.skills = merged.skills.filter((s) => {
    const key = s.name.toLowerCase();
    if (seenSkills.has(key)) return false;
    seenSkills.add(key);
    return true;
  });

  // Deduplicate projects by repoUrl or title
  const seenProjects = new Set<string>();
  merged.projects = merged.projects.filter((p) => {
    const key = p.repoUrl || p.title.toLowerCase();
    if (seenProjects.has(key)) return false;
    seenProjects.add(key);
    return true;
  });

  // Deduplicate links by URL
  const seenLinks = new Set<string>();
  merged.links = merged.links.filter((l) => {
    const key = l.url.toLowerCase();
    if (seenLinks.has(key)) return false;
    seenLinks.add(key);
    return true;
  });

  return merged;
}

/**
 * Generate a URL-friendly handle from name or email
 */
function generateHandle(firstName?: string, lastName?: string, email?: string): string {
  if (firstName) {
    const name = `${firstName}${lastName || ''}`
      .toLowerCase()
      .replace(/[^a-z0-9]/g, '')
      .slice(0, 20);
    if (name.length >= 3) return name;
  }

  if (email) {
    const username = email
      .split('@')[0]
      .toLowerCase()
      .replace(/[^a-z0-9]/g, '')
      .slice(0, 20);
    if (username.length >= 3) return username;
  }

  // Fallback: generate random handle
  return `user${Date.now().toString(36)}`;
}

/**
 * Ensure handle is unique by appending numbers if needed
 */
async function ensureUniqueHandle(baseHandle: string, excludeProfileId?: string): Promise<string> {
  let handle = baseHandle;
  let counter = 1;

  while (true) {
    const existing = await db.profile.findUnique({
      where: { handle },
      select: { id: true },
    });

    if (!existing || (excludeProfileId && existing.id === excludeProfileId)) {
      return handle;
    }

    handle = `${baseHandle}${counter}`;
    counter++;

    if (counter > 100) {
      // Safety: add random suffix
      handle = `${baseHandle}${Date.now().toString(36).slice(-4)}`;
      break;
    }
  }

  return handle;
}

/**
 * Map link type string to LinkType enum
 */
function mapLinkType(
  type: string
):
  | 'GITHUB'
  | 'LINKEDIN'
  | 'TWITTER'
  | 'PORTFOLIO'
  | 'BLOG'
  | 'DRIBBBLE'
  | 'BEHANCE'
  | 'YOUTUBE'
  | 'OTHER' {
  const typeMap: Record<
    string,
    | 'GITHUB'
    | 'LINKEDIN'
    | 'TWITTER'
    | 'PORTFOLIO'
    | 'BLOG'
    | 'DRIBBBLE'
    | 'BEHANCE'
    | 'YOUTUBE'
    | 'OTHER'
  > = {
    GITHUB: 'GITHUB',
    LINKEDIN: 'LINKEDIN',
    TWITTER: 'TWITTER',
    PORTFOLIO: 'PORTFOLIO',
    BLOG: 'BLOG',
    DRIBBBLE: 'DRIBBBLE',
    BEHANCE: 'BEHANCE',
    YOUTUBE: 'YOUTUBE',
    WEBSITE: 'PORTFOLIO',
    MEDIUM: 'BLOG',
    DEVTO: 'BLOG',
  };

  return typeMap[type.toUpperCase()] || 'OTHER';
}
