'use client';

import { motion } from 'framer-motion';
import { Edit, Sparkles, X } from 'lucide-react';
import Link from 'next/link';

import { Button } from '@/components/ui/button';

interface AutoGeneratedBannerProps {
  onDismissAction: () => void;
}

export function AutoGeneratedBanner({ onDismissAction }: AutoGeneratedBannerProps) {
  return (
    <motion.div
      initial={{ opacity: 0, y: -20 }}
      animate={{ opacity: 1, y: 0 }}
      exit={{ opacity: 0, y: -20 }}
      className="border-b bg-gradient-to-r from-primary/5 via-primary/10 to-primary/5"
    >
      <div className="container flex items-center justify-between gap-4 py-3">
        <div className="flex items-center gap-3">
          <div className="flex h-8 w-8 items-center justify-center rounded-full bg-primary/10">
            <Sparkles className="h-4 w-4 text-primary" />
          </div>
          <div>
            <p className="text-sm font-medium">Your profile was auto-generated from your imports</p>
            <p className="text-xs text-muted-foreground">
              Edit anytime—nothing is final. Your profile is already live!
            </p>
          </div>
        </div>
        <div className="flex items-center gap-2">
          <Link href="/builder">
            <Button variant="outline" size="sm" className="gap-2">
              <Edit className="h-3 w-3" />
              Customize
            </Button>
          </Link>
          <Button variant="ghost" size="icon" onClick={onDismissAction} className="h-8 w-8">
            <X className="h-4 w-4" />
            <span className="sr-only">Dismiss</span>
          </Button>
        </div>
      </div>
    </motion.div>
  );
}
