import { db } from '@/lib/db';
import { getPublicProfile } from '@/services/profile.service';
import { auth } from '@clerk/nextjs/server';
import { redirect } from 'next/navigation';
import { ProfilePreview } from './profile-preview';

export const dynamic = 'force-dynamic';

export default async function MyProfilePage() {
  const { userId } = await auth();

  if (!userId) {
    redirect('/sign-in');
  }

  // Get user with profile handle
  const user = await db.user.findUnique({
    where: { clerkId: userId },
    include: {
      profile: {
        select: { handle: true },
      },
    },
  });

  // If no profile, redirect to onboarding
  if (!user?.profile?.handle) {
    redirect('/onboarding');
  }

  // Get the public profile (with hidden sections filtered out)
  // This shows the owner exactly what visitors will see
  const publicProfile = await getPublicProfile(user.profile.handle);

  if (!publicProfile) {
    redirect('/onboarding');
  }

  return <ProfilePreview profile={publicProfile} showAutoGeneratedBanner={false} isOwner={true} />;
}
