'use client';

import { UserButton } from '@clerk/nextjs';
import { AnimatePresence, motion } from 'framer-motion';
import { Edit, ExternalLink, Eye, Settings } from 'lucide-react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useState } from 'react';

import { ViewSwitcher } from '@/app/u/[handle]/view-switcher';
import { PortfolioView } from '@/app/u/[handle]/views/portfolio-view';
import { ResumeView } from '@/app/u/[handle]/views/resume-view';
import { SnapshotView } from '@/app/u/[handle]/views/snapshot-view';
import { TimelineView } from '@/app/u/[handle]/views/timeline-view';
import { AutoGeneratedBanner } from '@/components/AutoGeneratedBanner';
import { Logo } from '@/components/Logo';
import { Button } from '@/components/ui/button';

import type { ProfileView, PublicProfile } from '@/types';

interface ProfilePreviewProps {
  profile: PublicProfile;
  showAutoGeneratedBanner: boolean;
  isOwner: boolean;
}

export function ProfilePreview({
  profile,
  showAutoGeneratedBanner: initialShowBanner,
  isOwner,
}: ProfilePreviewProps) {
  const router = useRouter();
  const [currentView, setCurrentView] = useState<ProfileView>('resume');
  const [showBanner, setShowBanner] = useState(initialShowBanner);

  const handleViewChange = (view: ProfileView) => {
    setCurrentView(view);
  };

  const handleDismissBanner = async () => {
    setShowBanner(false);

    // Persist dismissal
    try {
      await fetch('/api/profile/dismiss-banner', {
        method: 'POST',
      });
    } catch {
      // Silent fail - banner will stay dismissed for this session
    }
  };

  const publicUrl = `/u/${profile.handle}`;

  return (
    <div className="min-h-screen bg-gradient-to-b from-muted/30 to-background">
      {/* Owner Navigation Bar */}
      {isOwner && (
        <header className="sticky top-0 z-50 border-b bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60">
          <div className="flex h-16 items-center justify-between px-4 sm:px-6 lg:px-8">
            <Logo href="/me" size="md" />
            <div className="flex items-center gap-3">
              <Link href={publicUrl} target="_blank">
                <Button variant="ghost" size="sm" className="gap-2">
                  <Eye className="h-4 w-4" />
                  <span className="hidden sm:inline">Public View</span>
                  <ExternalLink className="h-3 w-3" />
                </Button>
              </Link>
              <Link href="/builder">
                <Button variant="outline" size="sm" className="gap-2">
                  <Edit className="h-4 w-4" />
                  <span className="hidden sm:inline">Edit</span>
                </Button>
              </Link>
              <Link href="/settings">
                <Button variant="ghost" size="icon">
                  <Settings className="h-4 w-4" />
                </Button>
              </Link>
              <UserButton
                appearance={{
                  elements: {
                    avatarBox: 'h-8 w-8',
                  },
                }}
              />
            </div>
          </div>
        </header>
      )}

      {/* Auto-generated Banner */}
      <AnimatePresence>
        {showBanner && <AutoGeneratedBanner onDismissAction={handleDismissBanner} />}
      </AnimatePresence>

      {/* View Switcher */}
      <ViewSwitcher currentView={currentView} onViewChange={handleViewChange} />

      {/* Profile Content */}
      <AnimatePresence mode="wait">
        <motion.main
          key={currentView}
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          exit={{ opacity: 0, y: -20 }}
          transition={{ duration: 0.3 }}
          className="container max-w-5xl py-8 pb-24"
        >
          {currentView === 'resume' && <ResumeView profile={profile} />}
          {currentView === 'portfolio' && <PortfolioView profile={profile} />}
          {currentView === 'timeline' && <TimelineView profile={profile} />}
          {currentView === 'snapshot' && <SnapshotView profile={profile} />}
        </motion.main>
      </AnimatePresence>

      {/* Footer */}
      <footer className="border-t bg-background py-6">
        <div className="container text-center text-sm text-muted-foreground">
          <p>
            Built with{' '}
            <a href="/" className="font-medium text-primary hover:underline">
              Follio
            </a>{' '}
            — Your professional identity, everywhere.
          </p>
        </div>
      </footer>
    </div>
  );
}
