-- CreateEnum
CREATE TYPE "MainPurpose" AS ENUM ('JOB_SEARCH', 'PERSONAL_BRAND', 'PROJECTS', 'RESEARCH', 'COMPANY', 'OTHER');

-- CreateEnum
CREATE TYPE "ConnectionStatus" AS ENUM ('CONNECTED', 'DISCONNECTED', 'ERROR', 'SYNCING');

-- AlterTable
ALTER TABLE "Profile" ADD COLUMN     "autoGeneratedDismissed" BOOLEAN NOT NULL DEFAULT false;

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "mainPurpose" "MainPurpose";

-- CreateTable
CREATE TABLE "ImportJob" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "source" "DataSource" NOT NULL,
    "status" "ImportStatus" NOT NULL DEFAULT 'PENDING',
    "inputType" TEXT,
    "inputData" JSONB,
    "progress" INTEGER NOT NULL DEFAULT 0,
    "currentStep" TEXT,
    "itemsFound" INTEGER NOT NULL DEFAULT 0,
    "itemsMerged" INTEGER NOT NULL DEFAULT 0,
    "result" JSONB,
    "error" TEXT,
    "startedAt" TIMESTAMP(3),
    "completedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "ImportJob_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "DataSourceConnection" (
    "id" TEXT NOT NULL,
    "profileId" TEXT NOT NULL,
    "source" "DataSource" NOT NULL,
    "status" "ConnectionStatus" NOT NULL DEFAULT 'CONNECTED',
    "externalId" TEXT,
    "accessToken" TEXT,
    "refreshToken" TEXT,
    "lastImportedAt" TIMESTAMP(3),
    "itemsImported" INTEGER NOT NULL DEFAULT 0,
    "importError" TEXT,
    "lastSyncAt" TIMESTAMP(3),
    "syncError" TEXT,
    "metadata" JSONB,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "DataSourceConnection_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "ImportJob_userId_idx" ON "ImportJob"("userId");

-- CreateIndex
CREATE INDEX "ImportJob_status_idx" ON "ImportJob"("status");

-- CreateIndex
CREATE INDEX "ImportJob_source_idx" ON "ImportJob"("source");

-- CreateIndex
CREATE INDEX "DataSourceConnection_profileId_idx" ON "DataSourceConnection"("profileId");

-- CreateIndex
CREATE INDEX "DataSourceConnection_source_idx" ON "DataSourceConnection"("source");

-- CreateIndex
CREATE UNIQUE INDEX "DataSourceConnection_profileId_source_key" ON "DataSourceConnection"("profileId", "source");

-- AddForeignKey
ALTER TABLE "ImportJob" ADD CONSTRAINT "ImportJob_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "DataSourceConnection" ADD CONSTRAINT "DataSourceConnection_profileId_fkey" FOREIGN KEY ("profileId") REFERENCES "Profile"("id") ON DELETE CASCADE ON UPDATE CASCADE;
